[package]
name = "bulk_allocator"
version = "0.1.0"
authors = ["Yoshida Shin <wbcchsyn@gmail.com>"]
edition = "2018"

description = "BulkAllocator implements trait core::alloc::AllocRef"
repository = "https://github.com/wbcchsyn/rust-bulk-allocator"
license = "LGPL-3.0-or-later OR Apache-2.0"
readme = "README.md"

keywords = ["alloc", "allocator", "memory", "AllocRef"]

categories = ["memory-management"]

[dependencies]
